[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/world-cup/world_cup_tournament_tracker.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/world-cup/world_cup_tournament_tracker.html"
  status = 200
